openapi: 3.0.0
info:
  title: API Website Portfolio 2025
  description: Dokumentasi API untuk website portfolio
  version: 1.0.0
servers:
  - url: http://localhost:3030
tags:
  - name: Auth
  - name: About
  - name: Education
  - name: Experiences
  - name: Project
paths: 
